import test from 'node:test';
import assert from 'node:assert/strict';
import { DEFAULT_DIARY_PROMPT, DEFAULT_MEMORY_PROMPT, assignMessageToAct, beginNextAct, buildCharacterContext, buildContinuityBlock, buildDialogue, buildDiaryBlock, buildDiaryPrompt, buildMemoryBlock, buildMemoryPrompt, buildRecallQuery, createState, extractMessage, filterPromptMessages, normalizeSettings, normalizeState, parseMemoryResponse, prependContinuityToHistory, recallMemories, validateTagPair } from '../core.js';

test('scene transition assigns the first next-scene user message', () => { const s=createState(1),first={is_user:true,mes:'第一幕',extra:{}};assignMessageToAct(s,first,1,0);s.acts[0].status='closed';s.status='pending_next_act';const next={is_user:true,mes:'第二幕',extra:{}};beginNextAct(s,next,1);assert.equal(s.currentActId,2);assert.equal(next.extra.scene_diary.actId,2); });
test('tag extraction uses full text when unset and reports unmatched configured tags', () => { assert.equal(extractMessage('<thinking>x</thinking>正文',{bodyTagPairs:[]}).body,'<thinking>x</thinking>正文');assert.equal(extractMessage('<now_plot>正文</now_plot>',{bodyTagPairs:[{open:'<now_plot>',close:'</now_plot>'}]}).body,'正文');assert.deepEqual(extractMessage('正文',{bodyTagPairs:[{open:'<now_plot>',close:'</now_plot>'}]}).errors,['未匹配任何正文标签对','提取后的正文为空']); });
test('dialogue keeps speaker ordering and time separate', () => { const messages=[{is_user:true,mes:'<u>你好</u>',extra:{scene_diary:{messageId:'u'}}},{name:'林',mes:'<p>晚安</p><time>初夏</time>',extra:{scene_diary:{messageId:'c'}}}];const out=buildDialogue(messages,{user:{bodyTags:['u']},character:{bodyTags:['p'],storyTimeTags:['time']}},'角色','玩家');assert.match(out.text,/玩家: 你好[\s\S]*林: 晚安[\s\S]*故事时间：初夏/); });
test('prompt filtering keeps system messages and current act only', () => { const old={mes:'old',extra:{scene_diary:{actId:1}}},current={mes:'new',extra:{scene_diary:{actId:2}}},system={is_system:true,mes:'s'};assert.deepEqual(filterPromptMessages([old,system,current],2),[system,current]); });
test('zero diary count injects no diary', () => { const s=createState(1);s.acts[0].status='closed';s.acts[0].diary='不应注入';assert.equal(buildDiaryBlock(s,{...s.settings,recentDiaryCount:0}), ''); });
test('memory parser validates sources and recall finds Chinese aliases', () => { const ms=parseMemoryResponse('{"memories":[{"category":"habit","title":"小名","content":"玩家喜欢被叫小兔","aliases":["兔兔"],"sourceMessageIds":["a","fake"]}]}',1,['a']);assert.deepEqual(ms[0].sourceMessageIds,['a']);const r=recallMemories(ms,'兔兔今天怎么样',{recallLimit:8,memoryTokenBudget:1200});assert.equal(r.selected[0].memory.title,'小名');assert.match(buildMemoryBlock(r),/仅作事实参考/); });
test('continuity block keeps diary immediately before memory at one injection point', () => { const s=createState(1);s.acts[0]={...s.acts[0],status:'closed',title:'约会',diary:'今天一起看了海。'};const recall={selected:[{memory:{category:'event',status:'active',title:'海边约会',content:'两人一起看海',storyTime:null}}]};const block=buildContinuityBlock(s,recall,s.settings);assert.ok(block.indexOf('近期日记')<block.indexOf('长期记忆'));assert.match(block,/今天一起看了海。[\s\S]*两人一起看海/); });
test('continuity is prepended before the complete chat history', () => { const history=[{is_user:false,mes:'历史回复'},{is_user:true,mes:'最新消息'}];assert.equal(prependContinuityToHistory(history,'日记\n\n长期记忆'),true);assert.equal(history[0].mes,'日记\n\n长期记忆');assert.equal(history[0].extra.type,'narrator');assert.equal(history[0].extra.scene_diary.injected,true);assert.deepEqual(history.slice(1).map(x=>x.mes),['历史回复','最新消息']); });
test('v1 data migrates without turning diaries into memories', () => { const s=normalizeState({version:1,currentActId:1,acts:[{id:1,status:'closed',diary:'旧日记',handoff:{}}]});assert.equal(s.version,2);assert.equal(s.acts[0].diary,'旧日记');assert.deepEqual(s.memories,[]); });
test('v0.2 content and user settings survive normalization unchanged', () => { const raw={version:2,currentActId:2,status:'active',acts:[{id:1,status:'closed',title:'旧幕',diary:'用户编辑过的日记',handoff:{location:'海边'}},{id:2,status:'active'}],memories:[{id:'kept',category:'event',title:'旧记忆',content:'用户已有的记忆',locked:true,createdAt:10,updatedAt:20}],settings:{recentDiaryCount:5,recallMessageCount:7,prompts:{diary:'用户日记提示词',memory:'用户记忆提示词'},extraction:{user:{bodyTagPairs:[{open:'<text>',close:'</text>'}]},character:{}}}};const s=normalizeState(raw);assert.equal(s.acts[0].diary,raw.acts[0].diary);assert.equal(s.memories[0].content,raw.memories[0].content);assert.equal(s.memories[0].locked,true);assert.equal(s.settings.recentDiaryCount,5);assert.equal(s.settings.recallMessageCount,7);assert.equal(s.settings.prompts.diary,'用户日记提示词');assert.deepEqual(s.settings.extraction.user.bodyTagPairs,[{open:'<text>',close:'</text>'}]); });
test('recall query inherits user and character body tags', () => { const messages=[{is_user:true,mes:'噪声<u>玩家想去海边</u><meta>隐藏</meta>',extra:{scene_diary:{messageId:'u',messageIndex:4}}},{is_user:false,mes:'前缀<c>角色答应周末同行</c><status>无效状态</status>',extra:{scene_diary:{messageId:'c',messageIndex:5}}}];const query=buildRecallQuery(messages,{user:{bodyTags:['u']},character:{bodyTags:['c']}});assert.equal(query.text,'玩家想去海边\n角色答应周末同行');assert.doesNotMatch(query.text,/噪声|隐藏|前缀|无效状态/);assert.deepEqual(query.errors,[]); });
test('recall query reports the exact floor when inherited tags do not match', () => { const query=buildRecallQuery([{is_user:true,mes:'没有正文标签',extra:{scene_diary:{messageId:'u',messageIndex:9}}}],{user:{bodyTags:['u']},character:{bodyTags:['c']}});assert.equal(query.errors[0].index,9);assert.match(query.errors[0].errors.join(''),/未匹配/); });
test('complete tag pairs are validated and legacy tag names migrate', () => { assert.deepEqual(validateTagPair({open:'<now_plot>',close:'</now_plot>'}),{open:'<now_plot>',close:'</now_plot>'});assert.equal(validateTagPair({open:'<now_plot>',close:'</plot>'}),null);const settings=normalizeSettings({extraction:{character:{bodyTags:['now_plot']},user:{}}});assert.deepEqual(settings.extraction.character.bodyTagPairs,[{open:'<now_plot>',close:'</now_plot>'}]); });
test('character context is limited to description personality and scenario', () => { const context=buildCharacterContext({description:'描述',personality:'性格',scenario:'场景',firstMessage:'不应出现',mesExamples:'不应出现'});assert.match(context,/描述/);assert.match(context,/性格/);assert.match(context,/场景/);assert.doesNotMatch(context,/不应出现/); });
test('editable prompt stays separate from hidden output format instructions', () => { const context=buildCharacterContext({description:'角色描述'}),diary=buildDiaryPrompt({characterName:'林',userName:'玩家',characterContext:context,dialogue:'玩家: 你好',targetLength:'短',prompt:'自定义 {{char}} 日记角色'}),memory=buildMemoryPrompt({characterName:'林',userName:'玩家',characterContext:context,dialogue:'玩家: 你好',prompt:'自定义记忆角色'});assert.match(diary,/自定义 林 日记角色/);assert.match(diary,/角色描述/);assert.match(diary,/"handoff"/);assert.match(memory,/自定义记忆角色/);assert.match(memory,/"memories"/);assert.equal(normalizeSettings({prompts:{}}).prompts.diary,DEFAULT_DIARY_PROMPT);assert.equal(normalizeSettings({prompts:{}}).prompts.memory,DEFAULT_MEMORY_PROMPT); });
