import test from 'node:test';
import assert from 'node:assert/strict';
import { assignMessageToAct, beginNextAct, buildDialogue, buildDiaryBlock, buildMemoryBlock, createState, extractMessage, filterPromptMessages, normalizeState, parseMemoryResponse, recallMemories } from '../core.js';

test('scene transition assigns the first next-scene user message', () => { const s=createState(1),first={is_user:true,mes:'第一幕',extra:{}};assignMessageToAct(s,first,1,0);s.acts[0].status='closed';s.status='pending_next_act';const next={is_user:true,mes:'第二幕',extra:{}};beginNextAct(s,next,1);assert.equal(s.currentActId,2);assert.equal(next.extra.scene_diary.actId,2); });
test('tag extraction uses full text when unset and reports unmatched configured tags', () => { assert.equal(extractMessage('<thinking>x</thinking>正文',{bodyTags:[]}).body,'<thinking>x</thinking>正文');assert.equal(extractMessage('<now_plot>正文</now_plot>',{bodyTags:['now_plot']}).body,'正文');assert.deepEqual(extractMessage('正文',{bodyTags:['now_plot']}).errors,['未匹配任何正文标签','提取后的正文为空']); });
test('dialogue keeps speaker ordering and time separate', () => { const messages=[{is_user:true,mes:'<u>你好</u>',extra:{scene_diary:{messageId:'u'}}},{name:'林',mes:'<p>晚安</p><time>初夏</time>',extra:{scene_diary:{messageId:'c'}}}];const out=buildDialogue(messages,{user:{bodyTags:['u']},character:{bodyTags:['p'],storyTimeTags:['time']}},'角色','玩家');assert.match(out.text,/玩家: 你好[\s\S]*林: 晚安[\s\S]*故事时间：初夏/); });
test('prompt filtering keeps system messages and current act only', () => { const old={mes:'old',extra:{scene_diary:{actId:1}}},current={mes:'new',extra:{scene_diary:{actId:2}}},system={is_system:true,mes:'s'};assert.deepEqual(filterPromptMessages([old,system,current],2),[system,current]); });
test('zero diary count injects no diary', () => { const s=createState(1);s.acts[0].status='closed';s.acts[0].diary='不应注入';assert.equal(buildDiaryBlock(s,{...s.settings,recentDiaryCount:0}), ''); });
test('memory parser validates sources and recall finds Chinese aliases', () => { const ms=parseMemoryResponse('{"memories":[{"category":"habit","title":"小名","content":"玩家喜欢被叫小兔","aliases":["兔兔"],"sourceMessageIds":["a","fake"]}]}',1,['a']);assert.deepEqual(ms[0].sourceMessageIds,['a']);const r=recallMemories(ms,'兔兔今天怎么样',{recallLimit:8,memoryTokenBudget:1200});assert.equal(r.selected[0].memory.title,'小名');assert.match(buildMemoryBlock(r),/仅作事实参考/); });
test('v1 data migrates without turning diaries into memories', () => { const s=normalizeState({version:1,currentActId:1,acts:[{id:1,status:'closed',diary:'旧日记',handoff:{}}]});assert.equal(s.version,2);assert.equal(s.acts[0].diary,'旧日记');assert.deepEqual(s.memories,[]); });
